language: python

dist: xenial

python:
  - "3.7"

# currently only checking basic things like syntax
# remind me to add a requirements.txt later
install:
  - pip install pyflakes

script:
  - pyflakes .
